name    'krisbuytaert-tmpwatch'
version '0.0.1'
source 'http://github.com/KrisBuytaert/puppet-tmpwatch.git'
author 'krisbuytaert'
license 'UNKNOWN'
summary 'Clean up a specific directory with files of a specific age'
description 'The tmpwatch module configures cronjobs with to clean up a specific directory with files of a specific age'
project_page 'http://github.com/KrisBuytaert/puppet-tmpwatch'
